a = 0
aa = 0
ab = 0
ac = 0
ad = 65535
ae = 0
af = 0
ag = 0
ah = 65535
ai = 0
aj = 0
ak = 0
al = 65535
am = 0
an = 0
ao = 0
ap = 0
aq = 0
ar = 0
as = 0
at = 0
au = 0
av = 0
aw = 0
ax = 0
ay = 65535
az = 0
b = 1674
ba = 0
bb = 0
bc = 65535
bd = 0
be = 0
bf = 0
bg = 65535
bh = 0
bi = 0
bj = 0
bk = 0
bl = 0
bm = 0
bn = 0
bo = 0
bp = 0
bq = 0
br = 0
bs = 0
bt = 65535
bu = 0
bv = 0
bw = 0
bx = 65535
by = 0
bz = 0
c = 0
ca = 0
cb = 65535
cc = 0
cd = 0
ce = 0
cf = 0
cg = 0
ch = 0
ci = 0
cj = 0
ck = 0
cl = 0
cm = 0
cn = 0
co = 65535
cp = 0
cq = 0
cr = 0
cs = 65535
ct = 0
cu = 0
cv = 0
cw = 65535
cx = 0
cy = 0
cz = 0
d = 418
da = 0
db = 0
dc = 0
dd = 0
de = 0
df = 0
dg = 0
dh = 0
di = 0
dj = 65535
dk = 0
dl = 0
dm = 0
dn = 65535
do = 0
dp = 0
dq = 0
dr = 65535
ds = 0
dt = 0
du = 0
dv = 0
dw = 0
dx = 0
dy = 0
dz = 0
e = 209
ea = 0
eb = 0
ec = 0
ed = 0
ee = 65535
ef = 0
eg = 0
eh = 0
ei = 65535
ej = 0
ek = 0
el = 0
em = 65535
en = 0
eo = 0
ep = 0
eq = 0
er = 0
es = 0
et = 0
eu = 0
ev = 0
ew = 0
ex = 0
ey = 0
ez = 65535
f = 52
fa = 0
fb = 0
fc = 0
fd = 65535
fe = 0
ff = 0
fg = 0
fh = 65535
fi = 0
fj = 0
fk = 0
fl = 0
fm = 0
fn = 0
fo = 0
fp = 0
fq = 0
fr = 0
fs = 0
ft = 0
fu = 65535
fv = 0
fw = 0
fx = 0
fy = 65535
fz = 0
g = 16
ga = 0
gb = 0
gc = 65535
gd = 0
ge = 0
gf = 0
gg = 0
gh = 0
gi = 0
gj = 0
gk = 0
gl = 0
gm = 0
gn = 0
go = 0
gp = 65535
gq = 0
gr = 0
gs = 0
gt = 65535
gu = 0
gv = 0
gw = 0
gx = 65535
gy = 0
gz = 0
h = 16
ha = 0
hb = 0
hc = 0
hd = 0
he = 0
hf = 0
hg = 0
hh = 0
hi = 0
hj = 0
hk = 65535
hl = 0
hm = 0
hn = 0
ho = 65535
hp = 0
hq = 0
hr = 0
hs = 65535
ht = 0
hu = 0
hv = 0
hw = 0
hx = 0
hy = 0
hz = 0
i = 65519
ia = 0
ib = 0
ic = 0
id = 0
ie = 0
if = 65535
ig = 0
ih = 0
ii = 0
ij = 65535
ik = 0
il = 0
im = 0
in = 65535
io = 0
ip = 0
iq = 0
ir = 0
is = 0
it = 0
iu = 0
iv = 0
iw = 0
ix = 0
iy = 0
iz = 0
j = 0
ja = 65535
jb = 0
jc = 0
jd = 0
je = 65535
jf = 0
jg = 0
jh = 0
ji = 65535
jj = 0
jk = 0
jl = 0
jm = 0
jn = 0
jo = 0
jp = 0
jq = 0
jr = 0
js = 0
jt = 0
ju = 0
jv = 65535
jw = 0
jx = 0
jy = 0
jz = 65535
k = 0
ka = 0
kb = 0
kc = 0
kd = 65535
ke = 0
kf = 0
kg = 0
kh = 0
ki = 0
kj = 0
kk = 0
kl = 0
km = 0
kn = 0
ko = 0
kp = 0
kq = 65535
kr = 0
ks = 0
kt = 0
ku = 65535
kv = 0
kw = 0
kx = 0
ky = 65535
kz = 0
l = 0
la = 0
lb = 0
lc = 0
ld = 0
le = 0
lf = 0
lg = 0
lh = 0
li = 0
lj = 0
lk = 0
ll = 65535
lm = 0
ln = 0
lo = 0
lp = 65535
lq = 0
lr = 0
ls = 0
lt = 65535
lu = 0
lv = 0
lw = 0
lx = 0
ly = 0
lz = 0
m = 65535
ma = 0
n = 0
o = 0
p = 0
q = 65535
r = 0
s = 0
t = 0
u = 0
v = 837
w = 0
x = 0
y = 0
z = 0
